---
n13a:
    region_name: "params_n13a"
    radio_catalogue: "LoTSS_DR2_v100.srl_n13h.fits"
    combined_catalogue: "combined-north-13h.fits"
    dec_down: 52.
    dec_up: 62.
    ra_down: 230.
    ra_up: 250.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
n13b:
    region_name: "params_n13b"
    radio_catalogue: "LoTSS_DR2_v100.srl_n13h.fits"
    combined_catalogue: "combined-north-13h.fits"
    dec_down: 52.
    dec_up: 62.
    ra_down: 230.
    ra_up: 250.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
n13c:
    region_name: "params_n13c"
    radio_catalogue: "LoTSS_DR2_v100.srl_n13h.fits"
    combined_catalogue: "combined-north-13h.fits"
    dec_down: 52.
    dec_up: 62.
    ra_down: 230.
    ra_up: 250.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
n13d:
    region_name: "params_n13d"
    radio_catalogue: "LoTSS_DR2_v100.srl_n13h.fits"
    combined_catalogue: "combined-north-13h.fits"
    dec_down: 52.
    dec_up: 62.
    ra_down: 230.
    ra_up: 250.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
n13e:
    region_name: "params_n13e"
    radio_catalogue: "LoTSS_DR2_v100.srl_n13h.fits"
    combined_catalogue: "combined-north-13h.fits"
    dec_down: 52.
    dec_up: 62.
    ra_down: 230.
    ra_up: 250.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
s13a:
    region_name: "params_s13a"
    radio_catalogue: "LoTSS_DR2_v100.srl_s13h.fits"
    combined_catalogue: "combined-south-13h.fits"
    dec_down: 52.
    dec_up: 62.
    ra_down: 230.
    ra_up: 250.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
s13b:
    region_name: "params_s13b"
    radio_catalogue: "LoTSS_DR2_v100.srl_s13h.fits"
    combined_catalogue: "combined-south-13h.fits"
    dec_down: 52.
    dec_up: 62.
    ra_down: 230.
    ra_up: 250.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
s0a:
    region_name: "params_s0a"
    radio_catalogue: "LoTSS_DR2_v100.srl_s0h.fits"
    combined_catalogue: "combined-south-0h.fits"
    dec_down: 22.25
    dec_up: 32.
    ra_down: 0.
    ra_up: 20.5
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
