---
n13:
    region_name: "params_n13"
    radio_catalogue: "LoTSS_DR2_v110_masked.srl.fits"
    combined_catalogue: "dr2_13h_north_withid.fits"
    dec_down: 25.
    dec_up: 80.
    ra_down: 95.
    ra_up: 295.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
s13:
    region_name: "params_s13"
    radio_catalogue: "LoTSS_DR2_v110_masked.srl.fits"
    combined_catalogue: "dr2_13h_south_withid.fits"
    dec_down: 15.
    dec_up: 40.
    ra_down: 95.
    ra_up: 295.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
s0a:
    region_name: "params_s0a"
    radio_catalogue: "LoTSS_DR2_v110_masked.srl.fits"
    combined_catalogue: "dr2_0h_south_withid.fits"
    dec_down: 15.
    dec_up: 45.
    ra_down: 0.
    ra_up: 45.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
s0b:
    region_name: "params_s0b"
    radio_catalogue: "LoTSS_DR2_v110_masked.srl.fits"
    combined_catalogue: "dr2_0h_south_withid.fits"
    dec_down: 15.
    dec_up: 45.
    ra_down: 315.
    ra_up: 360.
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
