---
hp_100:
    region_name: "params_100"
    radio_catalogue: "radio_100.fits"
    combined_catalogue: "optical_nn_100.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_848:
    region_name: "params_848"
    radio_catalogue: "radio_848.fits"
    combined_catalogue: "optical_nn_848.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_333:
    region_name: "params_333"
    radio_catalogue: "radio_333.fits"
    combined_catalogue: "optical_nn_333.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
g_333:
    region_name: "params_333_gauss"
    radio_catalogue: "gaussian_333.fits"
    combined_catalogue: "optical_nn_333.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_334:
    region_name: "params_334"
    radio_catalogue: "radio_334.fits"
    combined_catalogue: "optical_nn_334.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_332:
    region_name: "params_332"
    radio_catalogue: "radio_332.fits"
    combined_catalogue: "optical_nn_332.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_400:
    region_name: "params_400"
    radio_catalogue: "radio_400.fits"
    combined_catalogue: "optical_nn_400.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
g_400:
    region_name: "params_gauss_400"
    radio_catalogue: "gaussian_400.fits"
    combined_catalogue: "optical_nn_400.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_666:
    region_name: "params_666"
    radio_catalogue: "radio_666.fits"
    combined_catalogue: "optical_nn_666.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_845:
    region_name: "params_845"
    radio_catalogue: "radio_845.fits"
    combined_catalogue: "optical_nn_845.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
hp_1116:
    region_name: "params_1116"
    radio_catalogue: "radio_1116.fits"
    combined_catalogue: "optical_nn_1116.fits"
    max_major: 15
    colour_limits_post: [0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 4.1]
